Onnx runtime set allocator
RedisAI/RedisAI pull request #619
Opened 2021-02-25 08:48 UTC by alonre24

Introduce an API that allows setting a custom allocator for onnxruntime backend. We register RedisModule Alloc and Free functions as onnx allocator, so that onnx is now using them in model create, delete and run.
The memory usage of onnx (via redis allocator) and the number of accesses to the allocator is saved as part of the module info (defined in redisai.c), under a new section named "ai_memory_info". These are exported to RedisAI as new fields in the RAI_LoadedBackend struct.

2021-02-25 08:50 UTC, chayim approved these changes

2021-02-25 13:14 UTC, rafie commented on opt/build/onnxruntime/Dockerfile.arm
> +RUN ./pack.sh ${ONNXRUNTIME_VER} ${ARCH}
`pack.sh` can detect ${ARCH} by itself, no need to pass arg.

2021-02-25 13:15 UTC, rafie commented on opt/build/onnxruntime/Dockerfile.arm7
> +RUN ./pack.sh ${ONNXRUNTIME_VER} ${ARCH}
`pack.sh` can detect ${ARCH} by itself, no need to pass arg.

2021-02-25 13:19 UTC, rafie commented on opt/build/onnxruntime/pack.sh
> +PLATFORM="$2"
`PLATFORM=$($READIES/bin/platform -t)` should be used here.
And `linux-${PLATFORM}` should be replaced with `${PLATFORM}`.

2021-02-25 13:21 UTC, rafie requested changes
`tests/module/Makefile` should be replaced by a corresponding `CMakeLists.txt`.

2021-02-28 08:51 UTC, DvirDukhan commented on src/backends/onnxruntime.c
> +#define ONNX_API(x)                                                                                \
```suggestion
#define ONNX_VALIDATE_STATUS(x)                                                                                \
```

2021-02-28 08:51 UTC, DvirDukhan commented on src/backends/onnxruntime.c
> +#define ONNX_API(x)                                                                                \
add comments

2021-02-28 08:51 UTC, DvirDukhan commented on src/backends/onnxruntime.c
> +#endif
explain this important macro

2021-02-28 08:51 UTC, DvirDukhan commented on src/backends/onnxruntime.c
> +    atomic_fetch_add(&OnnxMemory, -1 * allocated_size);
```suggestion
    atomic_fetch_sub (&OnnxMemory, -1 * allocated_size);
```

2021-02-28 08:51 UTC, DvirDukhan commented on src/backends/onnxruntime.c
> +    atomic_fetch_add(&OnnxMemoryAccessCounter, 1);
```suggestion
    atomic_fetch_sub (&OnnxMemoryAccessCounter, 1);
```

2021-02-28 12:58 UTC, rafie commented
Instead of `test/module/Makefile`, better to use a `CMakeLists.txt`.
Take a look at this one, for example: https://github.com/RediSearch/RediSearch/blob/tests-with-.so/tests/so_tests/CMakeLists.txt
Should be very similar to that.

2021-03-11 20:38 UTC, DvirDukhan approved these changes

2021-03-11 21:15 UTC, rafie approved these changes

2021-03-11 21:29 UTC, merged