Support bool type for tensors
RedisAI/RedisAI pull request #775
Opened 2021-06-01 16:07 UTC by alonre24

We store tensor of type bool as a sequence of bits, where the minimal size is one byte (as UINT8).
Add validation that we do not overflow the size of the type of the tensor when setting new tensor.

2021-06-01 16:46 UTC, DvirDukhan requested changes
looks good
I think this PR should add the support for the appropriate backends also

2021-06-01 16:46 UTC, DvirDukhan commented on src/redis_ai_objects/tensor.h
> +static const char *RAI_DATATYPE_STR_BOOL = "BOOL";
```suggestion
static const char *RAI_DATATYPE_STR_BIT = "BIT";
```

2021-06-01 16:46 UTC, DvirDukhan commented on src/redis_ai_objects/tensor.c
> +    if (strcasecmp(typestr, "BOOL") == 0) {
```suggestion
    if (strcasecmp(typestr, "BIT") == 0) {
```

2021-06-01 16:46 UTC, DvirDukhan commented on src/redis_ai_objects/tensor.c
> +        uint max_abs_val = (uint)1 << (uint)(dtype.bits - 1);
```suggestion
        long long max_abs_val = (uint)1 << (uint)(dtype.bits - 1) -1 ;
```

2021-06-01 16:46 UTC, DvirDukhan commented on src/redis_ai_objects/tensor.c
> +            return true;
please add a comment that we support up to 32 bits of unsigned int
also, please keep all the types in this functions as `long long`

2021-06-01 16:46 UTC, DvirDukhan commented on src/redis_ai_objects/tensor.c
> +            strcpy(dtypestr, RAI_DATATYPE_STR_BOOL);
```suggestion
            strcpy(dtypestr, RAI_DATATYPE_STR_BIT);
```

2021-06-01 16:46 UTC, DvirDukhan commented on src/redis_ai_objects/tensor.c
> +    if (empty || dtype.bits == 1) {
why?

2021-06-01 16:46 UTC, DvirDukhan commented on src/redis_ai_objects/tensor.c
> +            if (val % 2) {
```suggestion
            if (val ==1) {
```

2021-06-02 20:10 UTC, DvirDukhan commented on src/redis_ai_objects/tensor.c
> +        if (val > max_abs_val || val <= -1 * (long long)max_abs_val) {
`if (val > max_abs_val`
is signed and unsigned comparison, any edge cases?

2021-06-03 12:46 UTC, lantiga approved these changes
Looks good!

2021-06-03 19:34 UTC, DvirDukhan requested changes

2021-06-03 19:34 UTC, DvirDukhan commented on src/backends/tflite.c
> +        dl_device = kDLCUDA;
this is a breaking change
either introduce a new rdb encoding version or undo this change.

2021-06-03 19:34 UTC, DvirDukhan commented on src/backends/tensorflow.c
> +        case 1:
8?

2021-06-03 19:34 UTC, DvirDukhan commented on src/backends/libtorch_c/torch_c.cpp
> +        device.device_type = DLDeviceType::kDLCUDA;
breaking change

2021-06-04 13:14 UTC, alonre24 commented on src/backends/libtflite_c/tflite_c.cpp
> +    case DLDeviceType::kDLCUDA:
I guess so...

2021-06-04 13:17 UTC, alonre24 commented on src/backends/torch.c
> +        dl_device = kDLCUDA;
This isn't a breaking change. dlpack renamed this in their last release: https://github.com/dmlc/dlpack/releases
but the numeric value has not changed.

2021-06-04 13:18 UTC, alonre24 commented on src/backends/tensorflow.c
> +        case 1:
right! thanks

2021-06-06 08:27 UTC, DvirDukhan approved these changes

2021-06-06 09:55 UTC, merged