Fix to support AI-LIGHT with redis 6.0.6
RedisAI/RedisAI pull request #896
Opened 2022-01-10 16:50 UTC by alonre24

Add `getRedisVersion` util, and use it instead of RM_getServerVersion which is not supported in old versions.

2022-01-10 17:40 UTC, GuyAv46 requested changes

2022-01-10 17:40 UTC, GuyAv46 commented on src/execution/DAG/dag.c
> +            redis_version[1] >= 2) { // The following command is supported only from redis 6.2
```suggestion
        if (redis_version[0] > 6 || // The following command is supported only from redis 6.2
           (redis_version[0] == 6 && redis_version[1] >= 2)) {
```

2022-01-10 17:40 UTC, GuyAv46 commented on src/execution/command_parser.c
> +        redis_version[1] >= 2) { // The following command is supported only from redis 6.2
```suggestion
    if (redis_version[0] > 6 || // The following command is supported only from redis 6.2
       (redis_version[0] == 6 && redis_version[1] >= 2) {
```

2022-01-10 20:23 UTC, DvirDukhan requested changes

2022-01-10 20:23 UTC, DvirDukhan commented on src/execution/utils.h
> +void getRedisVersion(int *version_holder);
```suggestion
void getRedisVersion(int *major, int *minor, int *patch);
```

2022-01-10 20:23 UTC, DvirDukhan commented on src/execution/utils.h
> +void setRedisVersion();
```suggestion
void redisai_getRedisVersion();
```
if you change the name, let the reader know it is a module-level function

2022-01-11 08:12 UTC, alonre24 commented on src/execution/DAG/dag.c
> +            redis_version[1] >= 2) { // The following command is supported only from redis 6.2
Great catch, thanks!

2022-01-11 16:06 UTC, GuyAv46 reviewed
LGTM

2022-01-13 09:04 UTC, DvirDukhan approved these changes

2022-01-13 09:05 UTC, GuyAv46 approved these changes

2022-01-13 09:07 UTC, merged